In [137]:
import pandas as pd
from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.decomposition import PCA

# Step 1: Data Preprocessing
data = pd.read_csv('train.csv')
data1 = pd.read_csv('test.csv')

def get_constituency_type(constituency):
    if '(SC)' in constituency:
        return 1
    elif '(ST)' in constituency:
        return 2
    else:
        return 0

# Create the Constituency_type column for the training data
data['Constituency_type'] = data['Constituency ∇'].apply(get_constituency_type)
data1['Constituency_type'] = data1['Constituency ∇'].apply(get_constituency_type)

# Create a new column Is_Doctor based on 'Dr.' presence in Candidate column
data['Is_Doctor'] = data['Candidate'].apply(lambda x: 1 if 'Dr.' in x else 0)
data1['Is_Doctor'] = data1['Candidate'].apply(lambda x: 1 if 'Dr.' in x else 0)

data.drop(columns=['ID','Candidate','Constituency ∇'], inplace=True)
data1.drop(columns=['ID','Candidate','Constituency ∇'], inplace=True)

print(data.columns)
print(data1.columns)

def convert_to_lakhs(value):
    value = str(value)
    if value == "0":
        return 0
    elif 'Crore+' in value:
        number, unit = value.split()
        number = float(number.replace(",", ""))
        return int(number * 100000)
    elif 'Lac+' in value:
        number, unit = value.split()
        number = float(number.replace(",", ""))
        return int(number*1000)
    elif 'Thou+' in value:
        number, unit = value.split()
        number = float(number.replace(",", ""))
        return int(number*10)
    elif 'Hund+' in value:
        number, unit = value.split()
        number = float(number.replace(",", ""))
        return int(number)
    else:
        return int(value)

data["Total Assets"] = data["Total Assets"].apply(convert_to_lakhs)
data["Liabilities"] = data["Liabilities"].apply(convert_to_lakhs)
data1["Total Assets"] = data1["Total Assets"].apply(convert_to_lakhs)
data1["Liabilities"] = data1["Liabilities"].apply(convert_to_lakhs)
data['NetAssets_Liabilities'] = data['Total Assets'] - data['Liabilities']
data1['NetAssets_Liabilities'] = data1['Total Assets'] - data1['Liabilities']
min_value = data['NetAssets_Liabilities'].min()
data['NetAssets_Liabilities'] = data['NetAssets_Liabilities'] - min_value
min_value1 = data1['NetAssets_Liabilities'].min()
data1['NetAssets_Liabilities'] = data1['NetAssets_Liabilities'] - min_value1
data.drop(columns=['Total Assets','Liabilities'], inplace=True)
data1.drop(columns=['Total Assets','Liabilities'], inplace=True)

# Perform label encoding for Education column

from sklearn.preprocessing import LabelEncoder

# Encode the target variable
label_encoder = LabelEncoder()
data['Education'] = label_encoder.fit_transform(data['Education'])

# data['Education'] = data['Education'].astype('category').cat.codes

data = pd.get_dummies(data, columns=['Party','state'])
data1 = pd.get_dummies(data1, columns=['Party','state'])

# train_data_features = data.columns
# test_data_features = data1.columns
# missing_features_in_test = list(set(train_data_features) - set(test_data_features))
# missing_features_in_train = list(set(test_data_features) - set(train_data_features))

# if missing_features_in_test:
#     for feature in missing_features_in_test:
#         data1[feature] = 0

# if missing_features_in_train:
#     for feature in missing_features_in_train:
#         data[feature] = 0

# data = data[train_data_features]
# data1 = data1[train_data_features]

# data1.drop(columns=['Education'],inplace=True)
data

Index(['Party', 'Criminal Case', 'Total Assets', 'Liabilities', 'state',
       'Education', 'Constituency_type', 'Is_Doctor'],
      dtype='object')
Index(['Party', 'Criminal Case', 'Total Assets', 'Liabilities', 'state',
       'Constituency_type', 'Is_Doctor'],
      dtype='object')

,Criminal Case,Education,Constituency_type,Is_Doctor,NetAssets_Liabilities,Party_AAP,Party_AIADMK,Party_AITC,Party_BJD,Party_BJP,...,state_ODISHA,state_PUDUCHERRY,state_PUNJAB,state_RAJASTHAN,state_SIKKIM,state_TAMIL NADU,state_TRIPURA,state_UTTAR PRADESH,state_UTTARAKHAND,state_WEST BENGAL
0,4,3,0,0,28000000,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,0,1,1,0,7200000,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,0,9,0,1,7778000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,0,9,0,0,7976000,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,2,3,1,0,7239000,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2054,1,6,0,0,7151000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2055,0,0,0,0,7292000,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2056,0,5,0,1,8315000,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2057,1,1,0,0,9506000,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2058,0,5,0,0,7111000,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [138]:
data1

,Criminal Case,Constituency_type,Is_Doctor,NetAssets_Liabilities,Party_AAP,Party_AIADMK,Party_AITC,Party_BJD,Party_BJP,Party_CPI,...,state_ODISHA,state_PUDUCHERRY,state_PUNJAB,state_RAJASTHAN,state_SIKKIM,state_TAMIL NADU,state_TRIPURA,state_UTTAR PRADESH,state_UTTARAKHAND,state_WEST BENGAL
0,2,0,0,18000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,0,0,12287000,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,3,0,0,16900000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1,0,0,12300000,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,0,0,0,13500000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,0,0,0,12200000,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
1370,1,0,0,12087000,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
1371,1,0,0,12600000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1372,1,0,0,12295000,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1373,0,0,0,13000000,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [139]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import KFold

# Assuming 'data' is your original DataFrame
X = data.drop(columns=['Education'])
y = data['Education']

X_train_split, X_test_split, y_train_split, y_test_split = train_test_split(X, y, test_size=0.2, random_state=42)

# from sklearn.preprocessing import MinMaxScaler

# # Initialize the MinMaxScaler
# scaler = MinMaxScaler()

# # Fit the scaler on your training data
# scaler.fit(X_train_split)

# # Transform both the training and testing data
# X_train_scaled = scaler.transform(X_train_split)
# X_test_scaled = scaler.transform(X_test_split)



# kf = KFold(n_splits=5, shuffle=True, random_state=42)
# ans = 0
# # Iterate through the folds and train the Bernoulli Naive Bayes model
# for train_index, test_index in kf.split(data):
#     X_train, X_test = X.iloc[train_index], X.iloc[test_index]
#     y_train, y_test = y.iloc[train_index], y.iloc[test_index]

#     # Train the Bernoulli Naive Bayes model
#     bernoulli_nb = BernoulliNB(
#         alpha=0.5,
#         binarize=0.1,
#         fit_prior=True,
#         class_prior=None
#     )
#     bernoulli_nb.fit(X_train, y_train)

#     # Evaluate the model on the test set
#     score = bernoulli_nb.score(X_test, y_test)
#     print(f"Accuracy on fold: {score:.10f}")
#     ans += score

# print(ans/5)

bernoulli_nb = BernoulliNB(
    alpha=0.5,
    binarize=0.1,
    fit_prior=True,
    class_prior=None
)
bernoulli_nb.fit(X_train_split, y_train_split)

predictions = bernoulli_nb.predict(data1)
predictions = label_encoder.inverse_transform(predictions)
predictions

array(['12th Pass', 'Graduate', '12th Pass', ..., 'Graduate', 'Graduate',
       'Post Graduate'], dtype=object)

In [140]:
# from sklearn.metrics import f1_score
# f1 = f1_score(y_test_split, predictions, average='weighted')
# print("F1 Score:", f1)

In [141]:
df_pred = pd.DataFrame(predictions, columns=["Education"])
df_pred.to_csv('DoctorSpecialityIdentified.csv', index_label='ID')